/**
* Sistema de Controle de Serviços OS com acesso restrito
*
* Usado para fazer controlar uma Ordem de Serviços
*
* @author Cleber-Soft <cleber-soft@hotmail.com>
*
* @version 1.0
* @package SiS - Controle de Serviços OS
* 
* TELA DE PRINCIPAL
*/
package br.com.os.telas;

import java.text.DateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;
import br.com.os.dal.ModuloConexao;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Cleber'Nascimento
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    Connection conexao = null; 

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
        conexao = ModuloConexao.conector();
        //Abre a tela principal Maximizada
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //CENTRALIZA O JFRAMA (TELA PINCIPAL) 
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        MenuCadastro = new javax.swing.JMenu();
        MenuCliente = new javax.swing.JMenuItem();
        MenuOS = new javax.swing.JMenuItem();
        MenuUsuario = new javax.swing.JMenuItem();
        MenuRelatorio = new javax.swing.JMenu();
        MenuRelCli = new javax.swing.JMenuItem();
        MenuServico = new javax.swing.JMenuItem();
        MenuAjuda = new javax.swing.JMenu();
        MenuSobre = new javax.swing.JMenuItem();
        MenuOpcoes = new javax.swing.JMenu();
        MenuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SiS - Controle de  Serviço OS v1.0 - CleberSoft - Soluções em TI");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Desktop.setPreferredSize(new java.awt.Dimension(1041, 0));

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1041, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/os/icones/CLEBER.png"))); // NOI18N

        lblUsuario.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblUsuario.setText("Usuario");

        lblData.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblData.setText("Data");

        MenuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/os/icones/cadastro3.png"))); // NOI18N
        MenuCadastro.setText("Cadastro");
        MenuCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        MenuCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        MenuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/os/icones/cadastro3.png"))); // NOI18N
        MenuCliente.setText("Cliente");
        MenuCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuClienteActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuCliente);

        MenuOS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        MenuOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/os/icones/novo.png"))); // NOI18N
        MenuOS.setText("Nova OS");
        MenuOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOSActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuOS);

        MenuUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        MenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/os/icones/usuario.png"))); // NOI18N
        MenuUsuario.setText("Funcionarios");
        MenuUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuUsuario.setEnabled(false);
        MenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUsuarioActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuUsuario);

        Menu.add(MenuCadastro);

        MenuRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/os/icones/relatorio.png"))); // NOI18N
        MenuRelatorio.setText("Relatório");
        MenuRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        MenuRelCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        MenuRelCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/os/icones/relatorio2.png"))); // NOI18N
        MenuRelCli.setText("Clientes");
        MenuRelCli.setEnabled(false);
        MenuRelCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelCliActionPerformed(evt);
            }
        });
        MenuRelatorio.add(MenuRelCli);

        MenuServico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        MenuServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/os/icones/iconRelatorio4.png"))); // NOI18N
        MenuServico.setText("Serviços");
        MenuServico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuServico.setEnabled(false);
        MenuServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuServicoActionPerformed(evt);
            }
        });
        MenuRelatorio.add(MenuServico);

        Menu.add(MenuRelatorio);

        MenuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/os/icones/ajuda1.png"))); // NOI18N
        MenuAjuda.setText("Ajuda");
        MenuAjuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        MenuSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        MenuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/os/icones/sobre1.png"))); // NOI18N
        MenuSobre.setText("Sobre");
        MenuSobre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSobreActionPerformed(evt);
            }
        });
        MenuAjuda.add(MenuSobre);

        Menu.add(MenuAjuda);

        MenuOpcoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/os/icones/folder_options_15429.png"))); // NOI18N
        MenuOpcoes.setText("Opções");
        MenuOpcoes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        MenuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        MenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/os/icones/sair2.png"))); // NOI18N
        MenuSair.setText("Sair");
        MenuSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSairActionPerformed(evt);
            }
        });
        MenuOpcoes.add(MenuSair);

        Menu.add(MenuOpcoes);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblData)
                            .addComponent(lblUsuario))
                        .addGap(66, 66, 66)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblUsuario)
                        .addGap(39, 39, 39)
                        .addComponent(lblData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 220, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
        );

        setSize(new java.awt.Dimension(1376, 658));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // As linhas abaixo substituem a label daa pela atual do
        // Sistema ao iniciar o form
        Date data = new Date();
        DateFormat fomatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lblData.setText(fomatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void MenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSairActionPerformed
        // Exibe uma caixa de dialogo
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Sair ?", "Atenção !", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_MenuSairActionPerformed

    private void MenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSobreActionPerformed
        // Chamando a tela Sobre
        TelaSobre sobre = new TelaSobre(this, rootPaneCheckingEnabled);
        sobre.setModal(true);
        sobre.setLocationRelativeTo(Desktop);
        sobre.setVisible(true);
        //Desktop.add(usuario);
    }//GEN-LAST:event_MenuSobreActionPerformed

    private void MenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUsuarioActionPerformed
        // As linhas abaixo abre o form Tela usuario dentro do desktop pane
        TelaUsuario usuario = new TelaUsuario(this, rootPaneCheckingEnabled);
        usuario.setModal(true);
        usuario.setLocationRelativeTo(Desktop);
        usuario.setVisible(true);
        //Desktop.add(usuario);
    }//GEN-LAST:event_MenuUsuarioActionPerformed

    private void MenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuClienteActionPerformed
         // As linhas abaixo abre o form Tela cliente dentro do desktop pane
        TelaCliente cliente = new TelaCliente(this, rootPaneCheckingEnabled);
        cliente.setModal(true);
        cliente.setLocationRelativeTo(Desktop);
        cliente.setVisible(true);
        //Desktop.add(cliente);
    }//GEN-LAST:event_MenuClienteActionPerformed

    private void MenuOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOSActionPerformed
        // As linhas abaixo abre o form Tela cliente dentro do desktop pane
        TelaOS os = new TelaOS(this, rootPaneCheckingEnabled);
        os.setModal(true);
        os.setLocationRelativeTo(Desktop);
        os.setVisible(true);
        //Desktop.add(cliente);
    }//GEN-LAST:event_MenuOSActionPerformed

    private void MenuRelCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelCliActionPerformed
        // Gerando um relatorio de clientes
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a Impressão do Relatorio de Clientes","Atenção",JOptionPane.YES_NO_OPTION);
        if(confirma == JOptionPane.YES_NO_OPTION){
            //imprimindo relatorio com o framework JasperReports
            try {
                // jasperPrint para preparar a impressão de um relatorio
                JasperPrint print = JasperFillManager.fillReport("C:/report/clientes.jasper",null,conexao);
                //a linha abaixo exibe o reltorio atraves da clasee jasperViewer
                JasperViewer.viewReport(print,false);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_MenuRelCliActionPerformed

    private void MenuServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuServicoActionPerformed
        // Gerando um relatorio de servicos
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a Imissão do Relatorio de Srviços","Atenção",JOptionPane.YES_NO_OPTION);
        if(confirma == JOptionPane.YES_NO_OPTION){
            //imprimindo relatorio com o framework JasperReports
            try {
                // jasperPrint para preparar a impressão de um relatorio
                JasperPrint print = JasperFillManager.fillReport("C:/report/servicos.jasper",null,conexao);
                //a linha abaixo exibe o reltorio atraves da clasee jasperViewer
                JasperViewer.viewReport(print,false);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_MenuServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu MenuAjuda;
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenuItem MenuCliente;
    private javax.swing.JMenuItem MenuOS;
    private javax.swing.JMenu MenuOpcoes;
    public static javax.swing.JMenuItem MenuRelCli;
    private javax.swing.JMenu MenuRelatorio;
    private javax.swing.JMenuItem MenuSair;
    public static javax.swing.JMenuItem MenuServico;
    private javax.swing.JMenuItem MenuSobre;
    public static javax.swing.JMenuItem MenuUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
